apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: elasticsearch

spec:
    serviceName: "elasticsearch"
    replicas: 1
    selector:
        matchLabels:
            app: elasticsearch
    template:
        metadata:
            labels:
                app: elasticsearch
            annotations:
                vault.hashicorp.com/agent-inject: "true"
                vault.hashicorp.com/role: "policyrag"
                vault.hashicorp.com/agent-inject-secret-config: "policyrag/data/config"
                vault.hashicorp.com/agent-inject-template-config: |
                    {{- with secret "policyrag/data/config" -}}
                    export ELASTIC_PASSWORD="{{ .Data.data.ELASTIC_PASSWORD }}"
                    {{- end -}}
        spec:
            containers:
                - name: elasticsearch
                  image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
                  command: ["/bin/bash"]
                  args:
                      [
                          "-c",
                          "source /vault/secrets/config && exec /usr/local/bin/docker-entrypoint.sh eswrapper",
                      ]
                  env:
                      - name: discovery.type
                        value: single-node
                      - name: ES_JAVA_OPTS
                        value: "-Xms1g -Xmx1g"
                      - name: xpack.security.enabled
                        value: "true"
                  ports:
                      - containerPort: 9200
                        name: http
                      - containerPort: 9300
                        name: transport
                  volumeMounts:
                      - name: data
                        mountPath: /usr/share/elasticsearch/data
                  resources:
                      requests:
                          memory: "2Gi"
                          cpu: "500m"
                      limits:
                          memory: "3Gi"
                          cpu: "1000m"
    volumeClaimTemplates:
        - metadata:
              name: data
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
    name: elasticsearch
spec:
    selector:
        app: elasticsearch
    ports:
        - port: 9200
          name: http
        - port: 9300
          name: transport
