apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: policyrag-ingress
    annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
    rules:
        - host: policy-chat.example.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: policyrag
                            port:
                                number: 5000
